### ISSUE TITLE
tui-list-cell的border在h5不显示

### ISSUE THREAD

**Issue by gsoec** [dingyong0214/ThorUI-uniapp#18]
```css
.tui-list-cell::after {
  content: '';
  position: absolute;
  border-bottom: 1rpx solid #eaeef1;
  -webkit-transform: scaleY(0.5);
  transform: scaleY(0.5);
  bottom: 0;
  right: 0;
  left:0;
}
```
border-bottom: 1rpx在h5是0.5px，显示不出来
